basePath: /v1
definitions:
  models.LoginReq:
    properties:
      password:
        example: test1
        type: string
      username:
        example: test1
        type: string
    type: object
  models.RegisterReq:
    properties:
      email:
        example: test@example.com
        type: string
      first_name:
        example: test1
        type: string
      last_name:
        example: test1
        type: string
      password:
        example: test1
        type: string
      role:
        example: employee
        type: string
      username:
        example: test1
        type: string
    type: object
  models.ResponseData:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
      statusCode:
        type: integer
    type: object
  models.ResponseError:
    properties:
      message:
        type: string
      status:
        type: string
      statusCode:
        type: integer
    type: object
host: localhost:8080 // แก้ไขเป็น host และ port ที่แอปฯ คุณรัน
info:
  contact: {}
  description: This is the API documentation for the P2P application back-end.
  title: P2P Back-End API
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: User login with username and password
      parameters:
      - description: Login request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: User login
      tags:
      - User
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Registration request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/models.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: User registration
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
