basePath: /v1
definitions:
  p2p-back-end_modules_entities_models.LoginReq:
    properties:
      password:
        example: test1
        type: string
      username:
        example: test1
        type: string
    type: object
  p2p-back-end_modules_entities_models.RegisterReq:
    properties:
      email:
        example: test@example.com
        type: string
      first_name:
        example: test1
        type: string
      last_name:
        example: test1
        type: string
      password:
        example: test1
        type: string
      role:
        example: employee
        type: string
      username:
        example: test1
        type: string
    type: object
  p2p-back-end_modules_entities_models.ResponseData:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
      statusCode:
        type: integer
    type: object
  p2p-back-end_modules_entities_models.ResponseError:
    properties:
      message:
        type: string
      status:
        type: string
      statusCode:
        type: integer
    type: object
  p2p-back-end_modules_entities_models.UserInfo:
    properties:
      email:
        type: string
      name:
        type: string
      role:
        items:
          type: string
        type: array
      userId:
        type: string
      userName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the P2P application back-end.
  title: P2P Back-End API
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login user and set HttpOnly Cookie
      parameters:
      - description: Login Request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/p2p-back-end_modules_entities_models.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Login success (Token in Cookie)
          schema:
            allOf:
            - $ref: '#/definitions/p2p-back-end_modules_entities_models.ResponseData'
            - properties:
                data:
                  $ref: '#/definitions/p2p-back-end_modules_entities_models.UserInfo'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/p2p-back-end_modules_entities_models.ResponseData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/p2p-back-end_modules_entities_models.ResponseData'
      summary: Login
      tags:
      - Auth
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout user and clear access_token cookie
      produces:
      - application/json
      responses:
        "200":
          description: Logged out successfully
          schema:
            $ref: '#/definitions/p2p-back-end_modules_entities_models.ResponseData'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - Auth
  /v1/auth/profile:
    get:
      consumes:
      - application/json
      description: Get current user info from HttpOnly Cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/p2p-back-end_modules_entities_models.ResponseData'
            - properties:
                data:
                  $ref: '#/definitions/p2p-back-end_modules_entities_models.UserInfo'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get User Profile
      tags:
      - Auth
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Registration request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/p2p-back-end_modules_entities_models.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/p2p-back-end_modules_entities_models.ResponseData'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/p2p-back-end_modules_entities_models.ResponseError'
      summary: User registration
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
